# Generated by Django 4.2.1 on 2024-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_devicemessage_received_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_text', models.CharField(max_length=255)),
                ('order_file', models.FileField(upload_to='')),
            ],
        ),
    ]
