# Generated by Django 4.2.1 on 2023-11-27 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deviceprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprogram',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceprogram',
            name='errorCode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deviceprogram',
            name='executionState',
            field=models.CharField(choices=[('awaiting_execution', 'Awaiting Execution'), ('execution_started', 'Execution Started'), ('execution_finished_ok', 'Execution Finished with OK'), ('execution_failed_error_code', 'Execution Failed with Error Code')], default='awaiting_execution', max_length=30),
        ),
        migrations.AddField(
            model_name='deviceprogram',
            name='program_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deviceprogram',
            name='program_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
