# Generated by Django 4.2.1 on 2023-11-27 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deviceprogram_developer_deviceprogram_errorcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprogram',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceprogram',
            name='program_code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
